config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :places

      resources :journal_entries

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "journal_entries#index"
  resources :places
  resources :journal_entries
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
  mount_base64_uploader :image, ImageUploader

  # Direct associations

  belongs_to :place

  belongs_to :user,
             counter_cache: true

  # Indirect associations

  # Validations

  validates :date, presence: true

  validates :place_id, presence: true

  validates :title, presence: true

  validates :user_id, presence: true

  # Scopes

  def to_s
    user.to_s
  end
end

app/controllers/api/v1/journal_entries_controller.rb
class Api::V1::JournalEntriesController < Api::V1::GraphitiController
  def index
    journal_entries = JournalEntryResource.all(params)
    respond_with(journal_entries)
  end

  def show
    journal_entry = JournalEntryResource.find(params)
    respond_with(journal_entry)
  end

  def create
    journal_entry = JournalEntryResource.build(params)

    if journal_entry.save
      render jsonapi: journal_entry, status: :created
    else
      render jsonapi_errors: journal_entry
    end
  end

  def update
    journal_entry = JournalEntryResource.find(params)

    if journal_entry.update_attributes
      render jsonapi: journal_entry
    else
      render jsonapi_errors: journal_entry
    end
  end

  def destroy
    journal_entry = JournalEntryResource.find(params)

    if journal_entry.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: journal_entry
    end
  end
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  before_action :current_user_must_be_journal_entry_user,
                only: %i[edit update destroy]

  before_action :set_journal_entry, only: %i[show edit update destroy]

  def index
    @q = current_user.journal_entries.ransack(params[:q])
    @journal_entries = @q.result(distinct: true).includes(:user,
                                                          :place).page(params[:page]).per(10)
  end

  def show; end

  def new
    @journal_entry = JournalEntry.new
  end

  def edit; end

  def create
    @journal_entry = JournalEntry.new(journal_entry_params)

    if @journal_entry.save
      message = "JournalEntry was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @journal_entry, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @journal_entry.update(journal_entry_params)
      redirect_to @journal_entry,
                  notice: "Journal entry was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @journal_entry.destroy
    message = "JournalEntry was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to journal_entries_url, notice: message
    end
  end

  private

  def current_user_must_be_journal_entry_user
    set_journal_entry
    unless current_user == @journal_entry.user
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_journal_entry
    @journal_entry = JournalEntry.find(params[:id])
  end

  def journal_entry_params
    params.require(:journal_entry).permit(:user_id, :place_id, :title, :date,
                                          :description, :image)
  end
end

app/views/journal_entries/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Journal Entry #<%= journal_entry.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>User</dt>
      <dd>
        <% if @journal_entry.user.present? %>
          <%= link_to journal_entry.user, journal_entry.user %>
        <% end %>
      </dd>

      <dt>Place</dt>
      <dd>
        <% if @journal_entry.place.present? %>
          <%= link_to journal_entry.place, journal_entry.place %>
        <% end %>
      </dd>

      <dt>Title</dt>
      <dd><%= journal_entry.title %></dd>

      <dt>Date</dt>
      <dd><%= journal_entry.date %></dd>

      <dt>Description</dt>
      <dd><%= journal_entry.description %></dd>

      <dt>Image</dt>
      <dd>
        <%= cl_image_tag @journal_entry.image, class: "img-fluid" %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back journal_entry, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @journal_entry.user %>
          <%= link_to edit_journal_entry_url(journal_entry), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @journal_entry.user %>
          <%= link_to journal_entry, method: :delete, data: { confirm: "Do you really want to delete this journal_entry?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(journal_entry.updated_at) %> ago
  </div>
</div>

app/views/journal_entries/_form.html.erb
<% was_validated = journal_entry.errors.any? %>

<%= form_with(model: journal_entry, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">
    <% place_class = "form-control" %>
    <% place_was_invalid = journal_entry.errors.include?(:place) %>

    <% if was_validated %>
      <% if place_was_invalid %>
        <% place_class << " is-invalid" %>
      <% else %>
        <% place_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :place_id %>
    <%= f.collection_select :place_id, Place.all, :id, :to_s, {}, class: "form-control" %>
    <% if place_was_invalid %>
      <% journal_entry.errors.full_messages_for(:place).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% title_class = "form-control" %>
    <% title_was_invalid = journal_entry.errors.include?(:title) %>

    <% if was_validated %>
      <% if title_was_invalid %>
        <% title_class << " is-invalid" %>
      <% else %>
        <% title_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :title %>
    <%= f.text_field :title, class: title_class, placeholder: "Enter title" %>
    <% if title_was_invalid %>
      <% journal_entry.errors.full_messages_for(:title).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% date_class = "form-control" %>
    <% date_was_invalid = journal_entry.errors.include?(:date) %>

    <% if was_validated %>
      <% if date_was_invalid %>
        <% date_class << " is-invalid" %>
      <% else %>
        <% date_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :date %>
    <%= f.date_select :date, class: date_class, placeholder: "Enter date" %>
    <% if date_was_invalid %>
      <% journal_entry.errors.full_messages_for(:date).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% description_class = "form-control" %>
    <% description_was_invalid = journal_entry.errors.include?(:description) %>

    <% if was_validated %>
      <% if description_was_invalid %>
        <% description_class << " is-invalid" %>
      <% else %>
        <% description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :description %>
    <%= f.text_area :description, class: description_class, placeholder: "Enter description" %>
    <% if description_was_invalid %>
      <% journal_entry.errors.full_messages_for(:description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% image_class = "form-control" %>
    <% image_was_invalid = journal_entry.errors.include?(:image) %>

    <% if was_validated %>
      <% if image_was_invalid %>
        <% image_class << " is-invalid" %>
      <% else %>
        <% image_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
    <% if image_was_invalid %>
      <% journal_entry.errors.full_messages_for(:image).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/journal_entries/_journal_entries_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "journal_entries_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :description_cont, "Description contains" %>
    <%= f.text_field :description_cont, :class => "form-control", :placeholder => "Description contains" %>
  </div>

  <div class="form-group">
    <%= f.label :date, "Date" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='dategteqPicker' data-target-input="nearest">
          <%= f.text_field :date_gteq, :class => "form-control datetimepicker-input", :placeholder => "Date greater than or equal to", :data => {:target => '#dategteqPicker'} %>
          <div class="input-group-append" data-target='#dategteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='datelteqPicker' data-target-input="nearest">
          <%= f.text_field :date_lteq, :class => "form-control datetimepicker-input", :placeholder => "Date less than or equal to", :data => {:target => '#datelteqPicker'} %>
          <div class="input-group-append" data-target='#datelteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#dategteqPicker').datetimepicker({
              format: 'MM/DD/YYYY'
          });
          $('#datelteqPicker').datetimepicker({
              useCurrent: false,
              format: 'MM/DD/YYYY'
          });
          $('#dategteqPicker').on("dp.change", function (e) {
              $('#datelteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#datelteqPicker').on("dp.change", function (e) {
              $('#dategteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :title_cont, "Title contains" %>
    <%= f.text_field :title_cont, :class => "form-control", :placeholder => "Title contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :user_email_cont, "User email contains" %>
    <%= f.text_field :user_email_cont, :class => "form-control", :placeholder => "User email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :place_name_cont, "Place name contains" %>
    <%= f.text_field :place_name_cont, :class => "form-control", :placeholder => "Place name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/journal_entries" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#journal_entries_filters">
  Show filters
</a>

app/views/journal_entries/_list_item.html.erb
<%= link_to journal_entry, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= journal_entry %>
    <small class="text-muted">
      <%= time_ago_in_words(journal_entry.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/journal_entries/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Journal Entry #<%= @journal_entry.id %>
      </h2>

      <div class="card-body">
        <%= render "form", journal_entry: @journal_entry %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/journal_entries/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Journal Entries

      <%= link_to new_journal_entry_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "journal_entries/journal_entries_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Journal Entries

        <%= link_to new_journal_entry_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @journal_entries, partial: "list_item", as: :journal_entry %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @journal_entries, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/journal_entries/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Journal Entry
      </h2>

      <div class="card-body">
        <%= render "form", journal_entry: @journal_entry %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/journal_entries/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @journal_entry, partial: "card", as: :journal_entry %>
  </div>
</div>